/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _BingsuArrivalRoute } from '../pages/bingsu-arrival';
import { Route as _CheeringRoute } from '../pages/cheering';
import { Route as _DailyCompleteRoute } from '../pages/daily-complete';
import { Route as _IceCrushingRoute } from '../pages/ice-crushing';
import { Route as _IndexRoute } from '../pages/';
import { Route as _PolicyRoute } from '../pages/policy';
import { Route as _ProbabilityInfoRoute } from '../pages/probability-info';
import { Route as _ToppingUpRoute } from '../pages/topping-up';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/bingsu-arrival': (typeof _BingsuArrivalRoute)['_inputType'];
    '/cheering': (typeof _CheeringRoute)['_inputType'];
    '/daily-complete': (typeof _DailyCompleteRoute)['_inputType'];
    '/ice-crushing': (typeof _IceCrushingRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/policy': (typeof _PolicyRoute)['_inputType'];
    '/probability-info': (typeof _ProbabilityInfoRoute)['_inputType'];
    '/topping-up': (typeof _ToppingUpRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/bingsu-arrival': (typeof _BingsuArrivalRoute)['_outputType'];
    '/cheering': (typeof _CheeringRoute)['_outputType'];
    '/daily-complete': (typeof _DailyCompleteRoute)['_outputType'];
    '/ice-crushing': (typeof _IceCrushingRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/policy': (typeof _PolicyRoute)['_outputType'];
    '/probability-info': (typeof _ProbabilityInfoRoute)['_outputType'];
    '/topping-up': (typeof _ToppingUpRoute)['_outputType'];
  }
}
